version: "3.4"

services:
  weatherwebapi:
    container_name: WeatherWebAPI
    image: ${DOCKER_REGISTRY-}weatherwebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=1337
      - ASPNETCORE_Kestrel__Certificates__Default__Password=asdf
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/asdf.pfx
    ports:
      - "80:80"
      - "5000:443"

    build:
      context: .
      dockerfile: ../WeatherWebAPI/Dockerfile
    networks:
      - weather
    restart: unless-stopped

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro #<- cant find file
      #- ./docker.cert/https/:/root/.aspnet/https/ <- cant create container for service weatherapi: Duplicate mount point: /root/.aspnet/https
      #- ./docker.cert/https/:/root/.aspnet/https:ro <- Doesnt add asdf.pfx to destination but the APPDATA/Roaming/ASP.NET/https/ certificates are both there..?
      - ./docker.cert/https/:/https

networks:
  weather:
    external: true
